export enum RepositoryType {
  USERS = 'USERS_REPOSITORY',
  SETTINGS = 'SETTINGS_REPOSITORY',
  MEASURES = 'MEASURES_REPOSITORY',
  PLANS = 'PLANS_REPOSITORY',
  DAYS = 'DAYS_REPOSITORY',
  MEALS = 'MEALS_REPOSITORY',
  INGREDIENTS = 'INGREDIENTS_REPOSITORY',
  CATEGORIES = 'CATEGORIES_REPOSITORY',
}
